# Generated by Django 5.0.2 on 2024-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
