# Generated by Django 5.0.2 on 2024-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_delete_curso_producto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
