# Generated by Django 5.0.2 on 2024-03-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
    ]
