# Generated by Django 5.0.2 on 2024-03-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_remove_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
