# Generated by Django 5.0.2 on 2024-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_remove_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=models.CharField(max_length=255),
        ),
    ]
